### PR TITLE
Created a quit function

### PR DESCRIPTION
**Pull request by QuadX13**
User_Input typing quit creates a break exiting game

### CODE REVIEW

**Comment by clairette150** [comment]
Looks good! =D 
I would have gone about it a little differently: I would have set the is_running variable to false. (The variable exists for that purpose exactly.)

You added the pycache-files, we don't need them that. Seems lkike we forgot to make a .gitignore-file...

**Comment by QuadX13** [comment]
I have only watched three videos so I wasn't even aware of that variable lol, good info!

**Comment by clairette150** [comment]
closed

**Comment by clairette150** [comment]
I was trying to reopen the issue, not the merge request...  quit function is not added yet

**Pull request closed without merging**
